### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by MyraBaba** [brainqub3/jar3d_meta_expert#15]
fyi

latest version with chainlit

```


2024-08-04 20:10:10 - Exception in run:
Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/bc/Projects/meta_expert/agents/jar3d_cl.py", line 219, in run
    cor_string = cor_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
ERROR    2024-08-04 20:10:10 - Exception in run:
Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/bc/Projects/meta_expert/agents/jar3d_cl.py", line 219, in run
    cor_string = cor_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
ERROR    2024-08-04 20:10:10 - Exception in run:
Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/bc/Projects/meta_expert/agents/jar3d_cl.py", line 219, in run
    cor_string = cor_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2024-08-04 20:10:10 -   'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/bc/Projects/meta_expert/agents/jar3d_cl.py", line 219, in run
    cor_string = cor_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
ERROR    2024-08-04 20:10:10 -   'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/bc/Projects/meta_expert/agents/jar3d_cl.py", line 219, in run
    cor_string = cor_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
ERROR    2024-08-04 20:10:10 -   'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/bc/Projects/meta_expert/agents/jar3d_cl.py", line 219, in run
    cor_string = cor_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2024-08-04 20:10:10 - Execution time: 0.00 seconds
DEBUG    2024-08-04 20:10:10 - Execution time: 0.00 seconds
DEBUG    2024-08-04 20:10:10 - Execution time: 0.00 seconds
2024-08-04 20:10:10 - ========================================

INFO     2024-08-04 20:10:10 - ========================================

INFO     2024-08-04 20:10:10 - ========================================

2024-08-04 20:10:10 - 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/chainlit/utils.py", line 40, in wrapper
    return await user_function(**params_values)
  File "/home/bc/Projects/meta_expert/chat.py", line 206, in main
    final_answer = await cl.make_async(run_workflow)(state)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/asyncer/_main.py", line 358, in wrapper
    return await anyio.to_thread.run_sync(
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/lib/python3.10/asyncio/futures.py", line 285, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/bc/Projects/meta_expert/chat.py", line 183, in run_workflow
    for event in workflow.stream(state, configs):
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 963, in stream
    _panic_or_proceed(done, inflight, step)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 1489, in _panic_or_proceed
    raise exc
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/pregel/retry.py", line 66, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2406, in invoke
    input = step.invoke(input, config, **kwargs)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/utils.py", line 95, in invoke
    ret = context.run(self.func, input, **kwargs)
  File "/home/bc/Projects/meta_expert/chat.py", line 158, in <lambda>
    graph.add_node("meta_expert", lambda state: MetaExpert(**agent_kwargs).run(state=state))
  File "/home/bc/Projects/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/bc/Projects/meta_expert/agents/jar3d_cl.py", line 219, in run
    cor_string = cor_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
ERROR    2024-08-04 20:10:10 - 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/chainlit/utils.py", line 40, in wrapper
    return await user_function(**params_values)
  File "/home/bc/Projects/meta_expert/chat.py", line 206, in main
    final_answer = await cl.make_async(run_workflow)(state)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/asyncer/_main.py", line 358, in wrapper
    return await anyio.to_thread.run_sync(
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/lib/python3.10/asyncio/futures.py", line 285, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/bc/Projects/meta_expert/chat.py", line 183, in run_workflow
    for event in workflow.stream(state, configs):
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 963, in stream
    _panic_or_proceed(done, inflight, step)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 1489, in _panic_or_proceed
    raise exc
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/pregel/retry.py", line 66, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2406, in invoke
    input = step.invoke(input, config, **kwargs)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/utils.py", line 95, in invoke
    ret = context.run(self.func, input, **kwargs)
  File "/home/bc/Projects/meta_expert/chat.py", line 158, in <lambda>
    graph.add_node("meta_expert", lambda state: MetaExpert(**agent_kwargs).run(state=state))
  File "/home/bc/Projects/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/bc/Projects/meta_expert/agents/jar3d_cl.py", line 219, in run
    cor_string = cor_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
ERROR    2024-08-04 20:10:10 - 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/chainlit/utils.py", line 40, in wrapper
    return await user_function(**params_values)
  File "/home/bc/Projects/meta_expert/chat.py", line 206, in main
    final_answer = await cl.make_async(run_workflow)(state)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/asyncer/_main.py", line 358, in wrapper
    return await anyio.to_thread.run_sync(
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/lib/python3.10/asyncio/futures.py", line 285, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/bc/Projects/meta_expert/chat.py", line 183, in run_workflow
    for event in workflow.stream(state, configs):
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 963, in stream
    _panic_or_proceed(done, inflight, step)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 1489, in _panic_or_proceed
    raise exc
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/pregel/retry.py", line 66, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2406, in invoke
    input = step.invoke(input, config, **kwargs)
  File "/home/bc/Projects/meta_expert/venvMeta/lib/python3.10/site-packages/langgraph/utils.py", line 95, in invoke
    ret = context.run(self.func, input, **kwargs)
  File "/home/bc/Projects/meta_expert/chat.py", line 158, in <lambda>
    graph.add_node("meta_expert", lambda state: MetaExpert(**agent_kwargs).run(state=state))
  File "/home/bc/Projects/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/bc/Projects/meta_expert/agents/jar3d_cl.py", line 219, in run
    cor_string = cor_match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by BruceSuperProgramer** [comment]
I saw same issue after agent run a while.

**Comment by garkpit** [comment]
same thing here - when I switched to ollama with llama3.1:70b

**Comment by garkpit** [comment]
Now intermittently trying Groq

Top bit of logs when error starts: (hope this helps :)

2024-08-08 12:41:36 - Exception in run:
Traceback (most recent call last):
  File "/Users/Jay/Dev/AI/john-adeojo(brainqub3)/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Jay/Dev/AI/john-adeojo(brainqub3)/meta_expert/agents/jar3d_cl.py", line 222, in run
    cor_string = cor_match.group(1)
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
ERROR    2024-08-08 12:41:36 - Exception in run:
Traceback (most recent call last):
  File "/Users/Jay/Dev/AI/john-adeojo(brainqub3)/meta_expert/utils/logging.py", line 82, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Jay/Dev/AI/john-adeojo(brainqub3)/meta_expert/agents/jar3d_cl.py", line 222, in run
    cor_string = cor_match.group(1)
                 ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by john-adeojo** [comment]
I think this is soemthing to do with how the responses are being formatted. In my next iteration I plan to try and clean up the outputs to make them more structured.

**Comment by john-adeojo** [comment]
The most recent commit uses Docker to get up and running with Jar3d. The approach should cause less errors, please give it a try and let me know how it goes.
