### ISSUE TITLE
openai gpt-4o-mini

### ISSUE THREAD

**Issue by MyraBaba** [brainqub3/jar3d_meta_expert#26]
gpt also similar broken error: 

> 2024-08-15 17:15:56 - https://api.openai.com:443 "POST /v1/chat/completions HTTP/11" 200 None
DEBUG    2024-08-15 17:15:56 - https://api.openai.com:443 "POST /v1/chat/completions HTTP/11" 200 None
DEBUG    2024-08-15 17:15:56 - https://api.openai.com:443 "POST /v1/chat/completions HTTP/11" 200 None
Process ForkPoolWorker-6:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by john-adeojo** [comment]
This might be because I have not yet inetgrated openAI server into the knwoledge graph build. Assuming you are trying to use with hybrid retrieval.

**Comment by john-adeojo** [comment]
The most recent commit uses Docker to get up and running with Jar3d. The approach should cause less errors, please give it a try and let me know how it goes.
